import asyncio
import json
import time
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Confirmed
from core import solana_client, ai_engine, database, state
from core.config import RPC_URL, PROTOCOL_PROGRAM_ID, log

class ProtocolNodeManager:
    """
    Autonomous logic specialized for decentralized ProtoQol nodes.
    Listens to the blockchain and responds with 'Biy' wisdom and trust on-chain.
    """
    def __init__(self):
        self.client = AsyncClient(RPC_URL, commitment=Confirmed)
        self.is_running = False

    async def start(self):
        self.is_running = True
        log.info("[AUTONOMOUS_NODE] Engine started. Monitoring Solana for deeds...")
        
        # In a real decentralization scenario, we would use WebSockets.
        # For this prototype, we'll poll the recent activity.
        while self.is_running:
            try:
                await self.poll_new_proposals()
            except Exception as e:
                log.error(f"[AUTONOMOUS_NODE] Monitoring loop error: {e}")
            await asyncio.sleep(2.0)

    async def poll_new_proposals(self):
        """
        Scans for pending 'crystallizing' deeds in the global pulse and moves 
        them through the multi-agent consensus routine on-chain.
        """
        pending_events = [e for e in state.GLOBAL_PULSE if e.get("chain_status") == "voting"]
        
        for event in pending_events:
            # Avoid redundant processing
            if event.get("_node_processing"): continue
            event["_node_processing"] = True
            
            deed_id = event["deed_id"]
            log.info(f"[AUTONOMOUS_NODE] Detecting Pending Protocol Deed: {deed_id}")
            
            # This triggers the on-chain voting from our agents
            # The agents are already defined in solana_client.ORACLE_KEYS
            background_tasks = asyncio.create_task(self.execute_autonomous_consensus(event))

    async def execute_autonomous_consensus(self, event):
        """
        Simulates the individual agents (Biy) independently 'seeing' the event and voting.
        """
        nomad_pubkey = event["wallet_address"]
        deed_id = event["deed_id"]
        mission_id = event["mission_id"]
        points = event["impact_points"]
        agent_verdicts = event["ai_dialogue"] # Generated by analyze_deed earlier
        
        from core.config import MASTER_AUTHORITY_KEY
        proposer_pubkey = MASTER_AUTHORITY_KEY.pubkey()

        # Step 1: Sequential Decentralized Voting
        for agent_v in agent_verdicts:
            node_name = agent_v.get("node")
            verdict_bool = agent_v.get("verdict") == "ADAL"
            
            log.info(f"[NODE_{node_name}] Verifying payload for on-chain consensus...")
            try:
                tx = await solana_client.vote_deed_on_chain(
                    deed_id, node_name, verdict_bool, nomad_pubkey, proposer_pubkey
                )
                log.info(f"[NODE_{node_name}] ✓ Vote Crystallized: {tx[:16]}...")
            except Exception as e:
                log.warning(f"[NODE_{node_name}] ❌ Communication link failed: {e}")
            
            # Realistic network propagation delay
            await asyncio.sleep(1.0)

        # After all votes, finalize
        event["chain_status"] = "finalized"
        log.info(f"[AUTONOMOUS_NODE] Consensus Cycle Complete for {deed_id}.")

node_manager = ProtocolNodeManager()
